const initialState = [
	[
		{ color: 'white', type: 'rook' },
		{ color: 'white', type: 'knight' },
		{ color: 'white', type: 'bishop' },
		{ color: 'white', type: 'king' },
		{ color: 'white', type: 'queen' },
		{ color: 'white', type: 'bishop' },
		{ color: 'white', type: 'knight' },
		{ color: 'white', type: 'rook' },
	],
	[
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
		{ color: 'white', type: 'pawn' },
	],
	[null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null],
	[
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
		{ color: 'black', type: 'pawn' },
	],
	[
		{ color: 'black', type: 'rook' },
		{ color: 'black', type: 'knight' },
		{ color: 'black', type: 'bishop' },
		{ color: 'black', type: 'king' },
		{ color: 'black', type: 'queen' },
		{ color: 'black', type: 'bishop' },
		{ color: 'black', type: 'knight' },
		{ color: 'black', type: 'rook' },
	],
];

export default initialState;
